name: pdf
on: [push]

jobs: 
  pdf: 
    runs-on: "ubuntu-latest"
    steps:
      - name: Github Action for LaTeX
      - uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: |
            main.tex
      - name: listfiles
      - run: ls
            
            
  
      
