name: Compile PDF

on: [push]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
      
      - name: List files
        run: ls

            
            
  
      
